In [16]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg as la
from functools import reduce

%matplotlib inline

In [4]:
matrix_dims = 4

H1 = np.random.randn(matrix_dims, matrix_dims)
H2 = np.transpose(H1)
H = H1 + H2

In [6]:
evals, evecs = la.eig(H)

In [7]:
evals

array([ 1.64557716+0.j, -0.55090977+0.j, -4.29907481+0.j, -2.34542613+0.j])

In [8]:
evecs

array([[-0.41739248,  0.69178101,  0.3438129 ,  0.47855536],
       [ 0.68726748,  0.22168823,  0.66299877, -0.19735848],
       [-0.5663052 , -0.02134019,  0.37592658, -0.73315907],
       [-0.18095674, -0.68690462,  0.54854765,  0.44103534]])

In [15]:
# Sanity check: are all of the eigenvalues and eigenvectors correct?
index = 3
np.dot(H, evecs[:,index]) - evals[index]*evecs[:,index]

array([  4.44089210e-16+0.j,  -1.16573418e-15+0.j,   4.44089210e-16+0.j,
         4.44089210e-16+0.j])

In [19]:
H_test = reduce(np.dot, [evecs, np.diag(evals), np.transpose(evecs)]) 

In [20]:
H_test - H

array([[ -8.88178420e-16+0.j,   0.00000000e+00+0.j,   1.11022302e-16+0.j,
         -2.22044605e-16+0.j],
       [  0.00000000e+00+0.j,  -1.77635684e-15+0.j,  -2.22044605e-15+0.j,
         -2.22044605e-16+0.j],
       [  0.00000000e+00+0.j,  -2.22044605e-15+0.j,   8.88178420e-16+0.j,
         -3.33066907e-16+0.j],
       [  1.11022302e-16+0.j,  -2.22044605e-16+0.j,  -3.33066907e-16+0.j,
         -1.77635684e-15+0.j]])

Let's see what happens when we just change the eigenvalues but not the eigenvectors (it should be easier to change the eigenvalues, since we don't have any restriction on them, and according to the Jacobian formula, changing the eigenvectors should do nothing).  No, that's completely wrong.  You have to change everything.  

So actually, what would it be if I left the eigenvectors the same and just changed the eigenvalues?  Well, strictly speaking the Jacobian of this transformation doesn't really make sense.  

In [22]:
magnitude_of_change = 1e-3
d_evals = np.random.randn(matrix_dims)*magnitude_of_change

In [25]:
H_d1 = reduce(np.dot, [evecs, np.diag(evals + magnitude_of_change*np.array([1,0,0,0])), np.transpose(evecs)]) 
H_d2 = reduce(np.dot, [evecs, np.diag(evals + magnitude_of_change*np.array([0,1,0,0])), np.transpose(evecs)]) 
H_d3 = reduce(np.dot, [evecs, np.diag(evals + magnitude_of_change*np.array([0,0,1,0])), np.transpose(evecs)]) 
H_d4 = reduce(np.dot, [evecs, np.diag(evals + magnitude_of_change*np.array([0,0,0,1])), np.transpose(evecs)]) 

In [26]:
H_d1 - H

array([[  1.74216485e-04+0.j,  -2.86860281e-04+0.j,   2.36371534e-04+0.j,
          7.55299839e-05+0.j],
       [ -2.86860281e-04+0.j,   4.72336591e-04+0.j,  -3.89203150e-04+0.j,
         -1.24365684e-04+0.j],
       [  2.36371534e-04+0.j,  -3.89203150e-04+0.j,   3.20701581e-04+0.j,
          1.02476744e-04+0.j],
       [  7.55299839e-05+0.j,  -1.24365684e-04+0.j,   1.02476744e-04+0.j,
          3.27453425e-05+0.j]])